/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package run.java;

class AppTest {
    // No changes needed as the class is empty and serves as a placeholder for future tests.
}